# CMake generated Testfile for 
# Source directory: /Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/modules/dnn
# Build directory: /Users/dylanfurner/Desktop/2DConvolutionsLibrary/build_opencv/modules/dnn
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_dnn "/Users/dylanfurner/Desktop/2DConvolutionsLibrary/build_opencv/bin/opencv_test_dnn" "--gtest_output=xml:opencv_test_dnn.xml")
set_tests_properties(opencv_test_dnn PROPERTIES  LABELS "Main;opencv_dnn;Accuracy" WORKING_DIRECTORY "/Users/dylanfurner/Desktop/2DConvolutionsLibrary/build_opencv/test-reports/accuracy" _BACKTRACE_TRIPLES "/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/cmake/OpenCVUtils.cmake;1738;add_test;/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/cmake/OpenCVModule.cmake;1352;ocv_add_test_from_target;/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/modules/dnn/CMakeLists.txt;170;ocv_add_accuracy_tests;/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/modules/dnn/CMakeLists.txt;0;")
add_test(opencv_perf_dnn "/Users/dylanfurner/Desktop/2DConvolutionsLibrary/build_opencv/bin/opencv_perf_dnn" "--gtest_output=xml:opencv_perf_dnn.xml")
set_tests_properties(opencv_perf_dnn PROPERTIES  LABELS "Main;opencv_dnn;Performance" WORKING_DIRECTORY "/Users/dylanfurner/Desktop/2DConvolutionsLibrary/build_opencv/test-reports/performance" _BACKTRACE_TRIPLES "/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/cmake/OpenCVUtils.cmake;1738;add_test;/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/cmake/OpenCVModule.cmake;1251;ocv_add_test_from_target;/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/modules/dnn/CMakeLists.txt;175;ocv_add_perf_tests;/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/modules/dnn/CMakeLists.txt;0;")
add_test(opencv_sanity_dnn "/Users/dylanfurner/Desktop/2DConvolutionsLibrary/build_opencv/bin/opencv_perf_dnn" "--gtest_output=xml:opencv_perf_dnn.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_dnn PROPERTIES  LABELS "Main;opencv_dnn;Sanity" WORKING_DIRECTORY "/Users/dylanfurner/Desktop/2DConvolutionsLibrary/build_opencv/test-reports/sanity" _BACKTRACE_TRIPLES "/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/cmake/OpenCVUtils.cmake;1738;add_test;/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/cmake/OpenCVModule.cmake;1252;ocv_add_test_from_target;/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/modules/dnn/CMakeLists.txt;175;ocv_add_perf_tests;/Users/dylanfurner/Desktop/2DConvolutionsLibrary/opencv/modules/dnn/CMakeLists.txt;0;")
